#
# Autogenerated by Thrift Compiler (0.8.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#


class ChatMessage
  include ::Thrift::Struct, ::Thrift::Struct_Union
  CONTENT = 1
  SENDER = 2
  RECIPIENT = 3

  FIELDS = {
    CONTENT => {:type => ::Thrift::Types::STRING, :name => 'content'},
    SENDER => {:type => ::Thrift::Types::STRING, :name => 'sender'},
    RECIPIENT => {:type => ::Thrift::Types::STRING, :name => 'recipient'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

